services:
  - type: web
    name: tixcraft-checker-web
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget curl ca-certificates gnupg libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 libxshmfence1 libxss1 libxtst6 libx11-xcb1 libdrm2 fonts-liberation xdg-utils
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python web_main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
