services:
  - type: web
    name: tixcraft-checker-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python web_main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
