services:
  - type: worker
  - type: web
    name: tixcraft-checker
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: .
    startCommand: python web_main.py
    envVars: []
    plan: free