services:
  - type: web
    name: tixcraft-checker-web
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg ca-certificates
      pip install -r requirements.txt
      playwright install chromium --with-deps
    startCommand: python web_main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
